#!/bin/bash
#
# Copyright 2016 Vitalii Dmitriev 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enables/disables trackpoint for IBM/Lenovo Thinkpad laptops before *40
# (e.g. for x230 works, for x240 doesn't).
# TODO add *40 models and higher.

readonly TRACKPOINT="TPPS/2 IBM TrackPoint"
readonly WHEEL="Evdev Wheel Emulation"

input=$(xinput --list-props  "${TRACKPOINT}" | grep "${WHEEL} (")
enabled="${input: -1}"

if [ "${enabled}" -eq 1 ]; then
    xinput set-prop "${TRACKPOINT}" "${WHEEL}" 0
else
    xinput set-prop "${TRACKPOINT}" "${WHEEL}" 1
    xinput set-prop "${TRACKPOINT}" "${WHEEL} Button" 2
    xinput set-prop "${TRACKPOINT}" "${WHEEL} Timeout" 200 
fi
