#!/usr/bin/env bash
#
# Copyright © 2016 Vitalii Dmitriev 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Enables/disables trackpoint for IBM/Lenovo Thinkpad laptops before *40
# (e.g. for x230 works, for x240 doesn't).

readonly TRACKPOINT="TPPS/2 IBM TrackPoint"
readonly WHEEL="Evdev Wheel Emulation"
readonly MIDDLE="libinput Scroll Method Enabled"

enable_middle() {
    local enabled=${1}
    if [ "${enabled}" -eq 1 ]; then
        xinput set-prop "${TRACKPOINT}" "${MIDDLE}" 0, 0, 0
    else
        xinput set-prop "${TRACKPOINT}" "${MIDDLE}" 0, 0, 1
    fi
}

enable_wheel() {
    if [ "${enabled}" -eq 1 ]; then
        xinput set-prop "${TRACKPOINT}" "${WHEEL}" 0
    else
        xinput set-prop "${TRACKPOINT}" "${WHEEL}" 1
        xinput set-prop "${TRACKPOINT}" "${WHEEL} Button" 2
        xinput set-prop "${TRACKPOINT}" "${WHEEL} Timeout" 200 
    fi
}

input=$(xinput --list-props  "${TRACKPOINT}" | grep -i "${WHEEL} (")
if [ -z "${input}" ]; then
    input=$(xinput --list-props  "${TRACKPOINT}" | grep -i "${MIDDLE} (")
    enable_middle "${input: -1}"
else
    enable_wheel "${input: -1}"
fi
